{% set name = "nvtx" %}
{% set version = "0.2.11" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nvtx-{{ version }}.tar.gz
  sha256: 88d52cf424a0e68b1c05a6b1983fdfa1b35575f983aadc3118cee578491b043e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - cython
    - nvtx-c
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - nvtx
    - nvtx._lib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/NVIDIA/nvtx
  summary: PyNVTX - Python code annotation library
  license: Apache-2.0 WITH LLVM-exception
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - guysz-nvidia
    - conda-forge/cuda
    - bdice
    - shwina
