{% set name = "nvtx" %}
{% set version = "0.2.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nvtx-{{ version }}.tar.gz
  sha256: 9b88fd3e4108b6775b20a7345397c7fbf356c1931c0e22dc06bde541f26f98bb

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv
  ignore_run_exports_from:
    - cuda-nvtx

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - pip
    - python
    - cuda-nvtx
  run:
    - python

test:
  imports:
    - nvtx
    - nvtx._lib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/NVIDIA/nvtx
  summary: PyNVTX - Python code annotation library
  license: Apache-2.0 WITH LLVM-exception
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - shwina
